{{- range .Values.externalSecrets }}
{{- range $key, $value := . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore-secret 
  target:
    name: {{ $key }}   # This would be the name of the secret in K8
    creationPolicy: Owner
  {{- if eq $value "none" }}
  # You can get all of the secret content (recommended)
  dataFrom:
  - extract:
     key: {{ $key }} # This should be the name of the AWS secret

  {{- else }}
  ## Or you can get specific fields
  data:
  - secretKey: password # Name of the field to store inside the k8s secret
    remoteRef:
      key: {{ $key }} # Our AWS SecretsManager secret name goes here
      property: {{ $value }}   # Retrieve the Key/value of the AWS SecretsManager secret 
  {{- end }}

{{- end }}
{{- end }}

{{- $values := .Values -}}
{{- if .Values.externalSecretsSsm }}
{{- range $index, $value := .Values.externalSecretsSsm }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $value.name }}
spec:
  data:
    - secretKey: {{ $value.secret_name }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        version: {{ if contains "onebox" $value.ssm_name }}{{ $values.onebox.configVersion }}{{ else }}{{ $values.pod.configVersion }}{{ end }}
        key: {{ $value.ssm_name }}
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore-ssm
{{- end }}
{{- end }}