
{{ if .Values.pvc.enabled -}}
{{- $serviceName := include "nextgen.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $serviceName }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pvc.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClasses }}
{{- end }}