{{- if .Values.serviceAccount.create -}}
{{- $serviceName := include "nextgen.fullname" . }}
{{- $name := default .Values.irsaRole.name $serviceName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nextgen.serviceAccountName" . }}
  labels:
    {{- include "nextgen.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.irsaRole.enabled }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.irsaRole.account }}:policy/ack-{{ $name }}-policy
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


